<?xml version="1.0" encoding="utf-8"?>
<DataListDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DataList.xsd" Version="1.2">
  <DataList Id="747f96be-d2e3-466a-9d06-486f1cdec0b0" ConfigurationUri="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/09451df4-5b18-4474-b1bd-c5f625d4c2b7" PlcIdentifier="b84580d7-61ea-48ec-9861-abe43adbd376" TargetAttributes="PlcNext" TargetVersion="0/2020.0.0" UICulture="en-US">
    <Datum Uuid="fdb6f1ff-0399-4996-afff-cfec6b10f4b3">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="0" ObjectId="/PDList/PD[@uid=iodpdin]" SourceId="1c4661d2-10ca-4650-b083-963b1bee6704">
        <Label>DI4096</Label>
        <NodeId>0</NodeId>
        <DataType>Octetstring[512]</DataType>
        <OutputFrameId>1</OutputFrameId>
        <InputFrameId>0</InputFrameId>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset>0.0</Offset>
      </Role>
    </Datum>
    <Datum Uuid="0c353b8b-e257-48bf-9b01-4c436e4e5ad4">
      <FunctionText />
      <Role TypeName="ProcessDatum" ObjectIndex="1" ObjectId="/PDList/PD[@uid=iopdout]" SourceId="1c4661d2-10ca-4650-b083-963b1bee6704">
        <Label>DO4096</Label>
        <NodeId>0</NodeId>
        <DataType>Octetstring[512]</DataType>
        <OutputFrameId>1</OutputFrameId>
        <InputFrameId>0</InputFrameId>
        <IsSafe>False</IsSafe>
        <Access>Write</Access>
        <Offset>0.0</Offset>
      </Role>
    </Datum>
    <Datum Uuid="ae807d18-40f0-4651-966c-6f4a5563fe17">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="f2e0c0a0-1487-47c5-a72a-d3701aa8d4f0" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>PND_S1_PLC_RUN</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>FALSE</InitValue>
        <DataType>BOOL</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="0" ObjectId="/PDList/PD[@uid=pndpd1]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_4">
        <Label>PND_S1_PLC_RUN</Label>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="b2e506b5-4e43-4341-a5f1-2b04e2cf0fc8">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="c91bd181-753d-4869-80db-32517d62d06c" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>PND_S1_VALID_DATA_CYCLE</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>FALSE</InitValue>
        <DataType>BOOL</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="1" ObjectId="/PDList/PD[@uid=pndpd2]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_4">
        <Label>PND_S1_VALID_DATA_CYCLE</Label>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="fe6f0710-0257-4801-b8df-e2490df12ecd">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="1f7d05c1-ad28-4f2a-95f3-55759f6a6229" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>PND_S1_OUTPUT_STATUS_GOOD</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>FALSE</InitValue>
        <DataType>BOOL</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="2" ObjectId="/PDList/PD[@uid=pndpd3]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_4">
        <Label>PND_S1_OUTPUT_STATUS_GOOD</Label>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="a46cf355-0298-4697-a781-e34295307a6f">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="03402517-127c-4b46-be4d-654186ae9a2d" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>PND_S1_INPUT_STATUS_GOOD</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>FALSE</InitValue>
        <DataType>BOOL</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="3" ObjectId="/PDList/PD[@uid=pndpd4]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_4">
        <Label>PND_S1_INPUT_STATUS_GOOD</Label>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="ea80c21f-2ab8-4174-8705-83ce9c3f347f">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="389260df-75c1-4986-bd46-6f4b352d0d53" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>PND_S1_DATA_LENGTH</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>WORD#16#0</InitValue>
        <DataType>WORD</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="4" ObjectId="/PDList/PD[@uid=pndpd5]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_4">
        <Label>PND_S1_DATA_LENGTH</Label>
        <DataType>Bitstring16</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="453dc524-726f-4d74-bb90-fe6cd5d7db49">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="9c284e7a-de3f-4585-bb87-d5aa986b37bc" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>PND_S1_OUTPUTS</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue />
        <DataType>PND_IO_512</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="5" ObjectId="/PDList/PD[@uid=pndpd6]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_4">
        <Label>PND_S1_OUTPUTS</Label>
        <DataType>Octetstring[512]</DataType>
        <IsSafe>False</IsSafe>
        <Access>Write</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="ad6b20cb-a783-4511-b0ec-f5c4847ea448">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="de9315fb-986e-4f46-9c37-c0ee6d2dd3f3" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>PND_S1_INPUTS</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue />
        <DataType>PND_IO_512</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="6" ObjectId="/PDList/PD[@uid=pndpd7]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_4">
        <Label>PND_S1_INPUTS</Label>
        <DataType>Octetstring[512]</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="4fe76df1-d38d-4401-9499-18ce1dcc86c5">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="dc1e3b87-dc12-4cc8-80a0-b89cd4bad4f1" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>PND_IO_DRIVEN_BY_PLC</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>INT#0</InitValue>
        <DataType>INT</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="7" ObjectId="/PDList/PD[@uid=pndpd8]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_4">
        <Label>PND_IO_DRIVEN_BY_PLC</Label>
        <DataType>Signed16</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="44a868a2-ec2b-4e0c-abd6-ef4d93b9f3ef">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="4de09e13-a26c-44cf-a1be-e246be0b9ddb" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>AXIO_DIAG_STATUS_REG_HI</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>BYTE#16#0</InitValue>
        <DataType>BYTE</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="0" ObjectId="/PDList/PD[@uid=axiod0]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_ax">
        <Label>AXIO_DIAG_STATUS_REG_HI</Label>
        <DataType>Bitstring8</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="2e5f3914-6006-43a2-ac3e-5d6d98e949d1">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="fed01fc9-4df7-4a8a-9562-a6fdf209e05a" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>AXIO_DIAG_STATUS_REG_LOW</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>BYTE#16#0</InitValue>
        <DataType>BYTE</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="1" ObjectId="/PDList/PD[@uid=axiod1]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_ax">
        <Label>AXIO_DIAG_STATUS_REG_LOW</Label>
        <DataType>Bitstring8</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="84a1f344-5bc2-4fe3-94ef-7bcb573584df">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="94cd0364-1eb0-4dbe-9bf5-e30e04054df4" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>AXIO_DIAG_PARAM_REG_HI</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>BYTE#16#0</InitValue>
        <DataType>BYTE</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="2" ObjectId="/PDList/PD[@uid=axiod2]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_ax">
        <Label>AXIO_DIAG_PARAM_REG_HI</Label>
        <DataType>Bitstring8</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="82d2b4a1-69c0-42ca-a39f-85fbe754f8f2">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="a77d6f16-7ddf-4877-9f3b-a17b4acde2e2" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>AXIO_DIAG_PARAM_REG_LOW</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>BYTE#16#0</InitValue>
        <DataType>BYTE</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="3" ObjectId="/PDList/PD[@uid=axiod3]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_ax">
        <Label>AXIO_DIAG_PARAM_REG_LOW</Label>
        <DataType>Bitstring8</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="e94f4aff-b669-43d2-a75e-417a559b95f7">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="2e2b6e29-95c6-4d36-9cbf-e65f9879fb70" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>AXIO_DIAG_PARAM_2_REG_HI</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>BYTE#16#0</InitValue>
        <DataType>BYTE</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="4" ObjectId="/PDList/PD[@uid=axiod4]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_ax">
        <Label>AXIO_DIAG_PARAM_2_REG_HI</Label>
        <DataType>Bitstring8</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="7c64937b-172d-486d-9070-da3a76ce6eeb">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="152f9af6-fe65-4057-8256-d537dcfd3552" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>AXIO_DIAG_PARAM_2_REG_LOW</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>BYTE#16#0</InitValue>
        <DataType>BYTE</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="5" ObjectId="/PDList/PD[@uid=axiod5]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_ax">
        <Label>AXIO_DIAG_PARAM_2_REG_LOW</Label>
        <DataType>Bitstring8</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="761d3054-7bf2-410c-b9ef-d759d7516860">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="5c96ef54-8de8-4fdf-a1cc-17fbc1dd99e6" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>AXIO_DIAG_STATUS_REG_PF</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>FALSE</InitValue>
        <DataType>BOOL</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="6" ObjectId="/PDList/PD[@uid=axiod6]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_ax">
        <Label>AXIO_DIAG_STATUS_REG_PF</Label>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="8cda5a17-62ba-4745-8715-251dc8a43b48">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="dd104562-ce76-4a40-b938-91d468b77a38" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>AXIO_DIAG_STATUS_REG_BUS</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>FALSE</InitValue>
        <DataType>BOOL</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="7" ObjectId="/PDList/PD[@uid=axiod7]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_ax">
        <Label>AXIO_DIAG_STATUS_REG_BUS</Label>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="971bf69a-7d88-4b3f-bbaa-0bcebd110410">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="3c02fb09-5169-4198-ae02-251705a17cee" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>AXIO_DIAG_STATUS_REG_RUN</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>FALSE</InitValue>
        <DataType>BOOL</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="8" ObjectId="/PDList/PD[@uid=axiod8]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_ax">
        <Label>AXIO_DIAG_STATUS_REG_RUN</Label>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="992715bb-1594-4f65-be5d-16082e044c67">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="9c7454e3-77bf-4e56-818e-7922cc2dd644" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>AXIO_DIAG_STATUS_REG_ACT</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>FALSE</InitValue>
        <DataType>BOOL</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="9" ObjectId="/PDList/PD[@uid=axiod9]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_ax">
        <Label>AXIO_DIAG_STATUS_REG_ACT</Label>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="eaf31e0c-6d1e-401f-832d-f6394207ad20">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="da70c309-5cbf-42b3-bd9c-aa0821ddbe19" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>AXIO_DIAG_STATUS_REG_RDY</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>FALSE</InitValue>
        <DataType>BOOL</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="10" ObjectId="/PDList/PD[@uid=axiod10]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_ax">
        <Label>AXIO_DIAG_STATUS_REG_RDY</Label>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="2f73cf55-d1d6-4283-a17f-ec89086df4d3">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="1bdd8234-c551-4322-89b5-9204456cb5ec" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>AXIO_DIAG_STATUS_REG_SYSFAIL</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>FALSE</InitValue>
        <DataType>BOOL</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="11" ObjectId="/PDList/PD[@uid=axiod11]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_ax">
        <Label>AXIO_DIAG_STATUS_REG_SYSFAIL</Label>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="5985b134-d8c1-4a0f-8121-bdbc4bda409b">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="fb71a968-ce12-43b2-b6f8-d66498bccb14" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>AXIO_DIAG_STATUS_REG_PW</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>FALSE</InitValue>
        <DataType>BOOL</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="12" ObjectId="/PDList/PD[@uid=axiod12]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_ax">
        <Label>AXIO_DIAG_STATUS_REG_PW</Label>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="a1ec2a5e-ff93-46a9-91cd-98a48a3059b0">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="eb4fc504-47d1-43f7-b004-cc43cb97bd98" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>IB_DIAG_STATUS_REG_HI</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>BYTE#16#0</InitValue>
        <DataType>BYTE</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="0" ObjectId="/PDList/PD[@uid=pdib1]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_8">
        <Label>IB_DIAG_STATUS_REG_HI</Label>
        <DataType>Bitstring8</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="854e583c-2a72-41f9-af44-05b78adb3dae">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="a5ecdded-1e55-4dd2-8ef8-2a3effacd74a" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>IB_DIAG_STATUS_REG_LOW</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>BYTE#16#0</InitValue>
        <DataType>BYTE</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="1" ObjectId="/PDList/PD[@uid=pdib2]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_8">
        <Label>IB_DIAG_STATUS_REG_LOW</Label>
        <DataType>Bitstring8</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="62765bcc-12e0-4ee7-904c-c8a059d7384b">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="ca54227d-63dc-463d-9a03-51520d989d45" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>IB_DIAG_STATUS_REG_SYSFAIL</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>FALSE</InitValue>
        <DataType>BOOL</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="2" ObjectId="/PDList/PD[@uid=pdib3]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_8">
        <Label>IB_DIAG_STATUS_REG_SYSFAIL</Label>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="fecba4c5-bacd-42aa-bedb-34f9c5a946d3">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="63a7afa7-bf8c-429f-9a18-b19c08d48915" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>IB_DIAG_STATUS_REG_WARN</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>FALSE</InitValue>
        <DataType>BOOL</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="3" ObjectId="/PDList/PD[@uid=pdib4]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_8">
        <Label>IB_DIAG_STATUS_REG_WARN</Label>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="06f9910e-36fe-4227-97c2-bd7012ad31bc">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="27038139-4563-481a-8a5d-4b94e77a7120" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>IB_DIAG_STATUS_REG_QUAL</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>FALSE</InitValue>
        <DataType>BOOL</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="4" ObjectId="/PDList/PD[@uid=pdib5]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_8">
        <Label>IB_DIAG_STATUS_REG_QUAL</Label>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="10ca3869-a68e-41de-ad04-253ab51ad3db">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="b47a2287-6ea3-49c5-8d37-838869b1efd2" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>IB_DIAG_STATUS_REG_USER</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>FALSE</InitValue>
        <DataType>BOOL</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="5" ObjectId="/PDList/PD[@uid=pdib6]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_8">
        <Label>IB_DIAG_STATUS_REG_USER</Label>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="445dbc67-11fb-4ee3-8e76-1cfb24557564">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="a5f4864d-30bd-4e34-8590-7603fa1447d6" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>IB_DIAG_STATUS_REG_PF</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>FALSE</InitValue>
        <DataType>BOOL</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="6" ObjectId="/PDList/PD[@uid=pdib7]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_8">
        <Label>IB_DIAG_STATUS_REG_PF</Label>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="ff1b6de6-0c92-4860-b74e-a12ab491e407">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="4c825c28-4233-4dfe-8159-9ac4c7f0cdb2" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>IB_DIAG_STATUS_REG_BUS</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>FALSE</InitValue>
        <DataType>BOOL</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="7" ObjectId="/PDList/PD[@uid=pdib8]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_8">
        <Label>IB_DIAG_STATUS_REG_BUS</Label>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="329e576e-cd01-4c36-8513-ed17b5205acf">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="01fe8bd8-b6a2-481f-be05-0206271a26e2" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>IB_DIAG_STATUS_REG_CTRL</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>FALSE</InitValue>
        <DataType>BOOL</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="8" ObjectId="/PDList/PD[@uid=pdib9]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_8">
        <Label>IB_DIAG_STATUS_REG_CTRL</Label>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="7c40d2c8-938e-481d-b807-969b4737b18e">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="1420409d-66cd-4d0f-ad64-287f03388830" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>IB_DIAG_STATUS_REG_DTC</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>FALSE</InitValue>
        <DataType>BOOL</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="9" ObjectId="/PDList/PD[@uid=pdib10]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_8">
        <Label>IB_DIAG_STATUS_REG_DTC</Label>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="a40530ae-d70a-4155-8bd4-94776b2a8724">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="92f41021-d317-4003-8d94-e0c580fef1fa" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>IB_DIAG_STATUS_REG_RUN</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>FALSE</InitValue>
        <DataType>BOOL</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="10" ObjectId="/PDList/PD[@uid=pdib11]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_8">
        <Label>IB_DIAG_STATUS_REG_RUN</Label>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="9be96f1b-360a-47d9-aa0a-8cc17cc72c17">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="a702cb15-4e21-4398-988a-d64480528b5d" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>IB_DIAG_STATUS_REG_ACT</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>FALSE</InitValue>
        <DataType>BOOL</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="11" ObjectId="/PDList/PD[@uid=pdib12]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_8">
        <Label>IB_DIAG_STATUS_REG_ACT</Label>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="d7c3d270-3bbd-4b4c-a3af-a52c00df211b">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="cddfbfe3-87e5-421b-ab70-417f568d82cf" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>IB_DIAG_STATUS_REG_RDY</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>FALSE</InitValue>
        <DataType>BOOL</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="12" ObjectId="/PDList/PD[@uid=pdib13]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_8">
        <Label>IB_DIAG_STATUS_REG_RDY</Label>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="d2f05920-efb7-421e-9d23-f0ad329cbdc1">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="29a6e14b-b486-4c3c-bce2-45222c634bb5" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>IB_DIAG_PARAM_REG_HI</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>BYTE#16#0</InitValue>
        <DataType>BYTE</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="13" ObjectId="/PDList/PD[@uid=pdib14]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_8">
        <Label>IB_DIAG_PARAM_REG_HI</Label>
        <DataType>Bitstring8</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="e43a9a43-3b79-4501-805c-341416cbf314">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="d3e5f8af-dd70-4208-a86a-393ff5e47759" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>IB_DIAG_PARAM_REG_LOW</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>BYTE#16#0</InitValue>
        <DataType>BYTE</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="14" ObjectId="/PDList/PD[@uid=pdib15]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_8">
        <Label>IB_DIAG_PARAM_REG_LOW</Label>
        <DataType>Bitstring8</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="4dc55292-9e6d-4668-882a-0be2953e48be">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="1de104af-f183-4a43-a8db-0c24ed49e618" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>IB_DIAG_PARAM_2_REG_HI</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>BYTE#16#0</InitValue>
        <DataType>BYTE</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="15" ObjectId="/PDList/PD[@uid=pdib16]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_8">
        <Label>IB_DIAG_PARAM_2_REG_HI</Label>
        <DataType>Bitstring8</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="86e1d7ad-7244-44b4-aab0-1f88f7db169a">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="2cc13ea9-aba3-49bb-8737-edcf173f3f8f" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>IB_DIAG_PARAM_2_REG_LOW</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>BYTE#16#0</InitValue>
        <DataType>BYTE</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="16" ObjectId="/PDList/PD[@uid=pdib17]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_8">
        <Label>IB_DIAG_PARAM_2_REG_LOW</Label>
        <DataType>Bitstring8</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="46f989b9-2b49-41c7-a2a1-e6ff7fbcaf9d">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="fc294685-119f-45b8-aabf-c77cd6292c25" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>ESM_DATA</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue />
        <DataType>ESM_DAT</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="0" ObjectId="/PDList/PD[@uid=pdesm1]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_1">
        <Label>ESM_DATA</Label>
        <DataType>ESM_DAT</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="9a63bd46-1a87-4835-9f54-36dcbc58a497">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="4afa0e30-bf52-4f6a-83b6-40fc72707aa8" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>RTC</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue />
        <DataType>RTC_TYPE</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="1" ObjectId="/PDList/PD[@uid=pddi1]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_1">
        <Label>RTC</Label>
        <DataType>RTC_TYPE</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="7fb15367-2f7d-43cc-b851-9666bc2d93fd">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="58df9a4b-f3a7-471f-957c-e56e87541826" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>DEVICE_STATE</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue />
        <DataType>DEVICE_STATE_2152_TYPE</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="2" ObjectId="/PDList/PD[@uid=pddi2]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_1">
        <Label>DEVICE_STATE</Label>
        <DataType>DEVICE_STATE_2152_TYPE</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="9d305870-ef62-443e-b4f7-9597b9d7fcb0">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="cb978f06-1eb7-4656-9057-dac681aa8ef4" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>PNIO_SYSTEM_BF</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>FALSE</InitValue>
        <DataType>BOOL</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="8" ObjectId="/PDList/PD[@uid=pncpd1]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_4">
        <Label>PNIO_SYSTEM_BF</Label>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="c8578976-c67e-4bc3-8570-5d032d21c66f">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="87f31ae0-e30e-43f2-8f3d-7c400e95fec8" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>PNIO_SYSTEM_SF</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>FALSE</InitValue>
        <DataType>BOOL</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="9" ObjectId="/PDList/PD[@uid=pncpd2]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_4">
        <Label>PNIO_SYSTEM_SF</Label>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="514c4196-d8c8-4816-a515-eef0bfded2ac">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="c7dab69b-3839-4f71-a0b0-1630f4c454b1" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>PNIO_MAINTENANCE_DEMANDED</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>FALSE</InitValue>
        <DataType>BOOL</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="10" ObjectId="/PDList/PD[@uid=pncpd3]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_4">
        <Label>PNIO_MAINTENANCE_DEMANDED</Label>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="426883ca-4a33-4e62-9b3d-59435b44e7bf">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="be4c9e94-2445-4439-a281-ddf7c7040183" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>PNIO_MAINTENANCE_REQUIRED</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>FALSE</InitValue>
        <DataType>BOOL</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="11" ObjectId="/PDList/PD[@uid=pncpd4]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_4">
        <Label>PNIO_MAINTENANCE_REQUIRED</Label>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="1caa948f-8b6b-4c45-89e9-774507c125cd">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="d025f5a4-bc61-4ccd-b95c-f695326eadc8" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>PNIO_CONFIG_STATUS</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>WORD#16#0</InitValue>
        <DataType>WORD</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="12" ObjectId="/PDList/PD[@uid=pncpd5]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_4">
        <Label>PNIO_CONFIG_STATUS</Label>
        <DataType>Bitstring16</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="6fea7671-704f-45d6-be4a-eaa2cdb6279a">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="72e64d7d-5137-41f6-8750-98118bc3ee7b" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>PNIO_CONFIG_STATUS_ACTIVE</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>FALSE</InitValue>
        <DataType>BOOL</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="13" ObjectId="/PDList/PD[@uid=pncpd6]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_4">
        <Label>PNIO_CONFIG_STATUS_ACTIVE</Label>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="86bf508d-2a43-4069-9e1f-f9402c133000">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="03a376cd-0238-41ed-92a8-b74a4d4696aa" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>PNIO_CONFIG_STATUS_READY</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>FALSE</InitValue>
        <DataType>BOOL</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="14" ObjectId="/PDList/PD[@uid=pncpd7]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_4">
        <Label>PNIO_CONFIG_STATUS_READY</Label>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="c0bd5c4f-aa78-4961-8fb5-bde4af950fc6">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="57106ca2-572b-4d7d-a4b9-094d5955c449" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>PNIO_CONFIG_STATUS_CFG_FAULT</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>FALSE</InitValue>
        <DataType>BOOL</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="15" ObjectId="/PDList/PD[@uid=pncpd8]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_4">
        <Label>PNIO_CONFIG_STATUS_CFG_FAULT</Label>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="ef204237-fa98-434c-b91f-d17e200683cd">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="f7203f81-bef6-4a01-adc3-74cbd20f102f" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>PNIO_FORCE_FAILSAFE</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>FALSE</InitValue>
        <DataType>BOOL</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="16" ObjectId="/PDList/PD[@uid=pncpd9]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_4">
        <Label>PNIO_FORCE_FAILSAFE</Label>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Access>Write</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="030cd920-e53a-4ae2-8657-f76524131aeb">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="aebb716b-91c6-4b3d-a241-0f55b83f0785" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>PNIO_FORCE_PRIMARY</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>FALSE</InitValue>
        <DataType>BOOL</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="17" ObjectId="/PDList/PD[@uid=pncpd10]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_4">
        <Label>PNIO_FORCE_PRIMARY</Label>
        <DataType>BOOL</DataType>
        <IsSafe>False</IsSafe>
        <Access>Write</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="bacb7935-8852-4173-a6c6-bad305088ec8">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="00d4650d-407a-4c25-9929-9abb8931f6e9" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>IP_ACTIVE_SOCKETS</Name>
        <Address>%MW1.30000</Address>
        <IsHmi>False</IsHmi>
        <InitValue>UINT#0</InitValue>
        <DataType>UINT</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
        <Constraint TypeName="Ade.DataList.Constraints.Unconnectable, Ade.DataListImpl" Parameters="ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="7ce3742a-f684-4913-a032-9a707654007a">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="ebdf619f-fdc3-40af-8c74-c2ab62283bcf" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>TLS_ACTIVE_SOCKETS</Name>
        <Address>%MW1.30100</Address>
        <IsHmi>False</IsHmi>
        <InitValue>UINT#0</InitValue>
        <DataType>UINT</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
        <Constraint TypeName="Ade.DataList.Constraints.Unconnectable, Ade.DataListImpl" Parameters="ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="bd258abb-5829-4b71-9a6c-d29148089a83">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="3288a51a-a0a2-438f-ab08-95e91d561033" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>HMI_STATUS</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue />
        <DataType>HMI_STATUS_TYPE</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="0" ObjectId="/PDList/PD[@uid=hmipd001]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_3">
        <Label>HMI_STATUS</Label>
        <DataType>HMI_STATUS_TYPE</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="d5918e54-0745-4246-9107-d143d6256879">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="8d3096e6-6880-4a1b-9bbb-5e2e8765296f" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>HMI_CONTROL</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue />
        <DataType>HMI_CONTROL_TYPE</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="1" ObjectId="/PDList/PD[@uid=hmipd002]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_3">
        <Label>HMI_CONTROL</Label>
        <DataType>HMI_CONTROL_TYPE</DataType>
        <IsSafe>False</IsSafe>
        <Access>Write</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="27f5af69-941a-489a-b8e7-d1d55fba9e0f">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="2ab35482-1fc4-45dd-86d9-1d687999756e" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>EIPD_INPUTS</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue />
        <DataType>EIPD_IO_ARRAY</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="0" ObjectId="/PDList/PD[@uid=eip001]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_7">
        <Label>EIPD_INPUTS</Label>
        <DataType>EIPD_IO_ARRAY</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="77142c55-72a3-45bc-8e70-11aec5297d6e">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="66f43bf7-44d3-440f-95c8-f82ebf96d463" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>EIPD_OUTPUTS</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue />
        <DataType>EIPD_IO_ARRAY</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="1" ObjectId="/PDList/PD[@uid=eip002]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_7">
        <Label>EIPD_OUTPUTS</Label>
        <DataType>EIPD_IO_ARRAY</DataType>
        <IsSafe>False</IsSafe>
        <Access>Write</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="15f51bbf-e345-435b-be66-66037706fb7b">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="6d1b591a-0c5d-435e-9d7f-f15586a31881" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>EIPD_VALID_DATA_CYCLE</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>FALSE</InitValue>
        <DataType>BOOL</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="2" ObjectId="/PDList/PD[@uid=eip003]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_7">
        <Label>EIPD_VALID_DATA_CYCLE</Label>
        <DataType>Boolean</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="d8993079-2be0-486e-822e-49987817cde2">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="7c386bef-0870-4bac-8cad-3b8a37212001" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>EIPD_PEER_IDLE</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>FALSE</InitValue>
        <DataType>BOOL</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="3" ObjectId="/PDList/PD[@uid=eip004]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_7">
        <Label>EIPD_PEER_IDLE</Label>
        <DataType>Boolean</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="d2d42752-7083-4fce-b7e1-a47cb78286ba">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="f467c5b5-68ed-4093-8478-cda82d22b400" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>EIPD_PEER_RUN</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>FALSE</InitValue>
        <DataType>BOOL</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="4" ObjectId="/PDList/PD[@uid=eip005]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_7">
        <Label>EIPD_PEER_RUN</Label>
        <DataType>Boolean</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="2be6bf5f-6326-4f22-8c17-14a29de77a22">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="db630005-8bdb-4bba-849e-b92dd9ef16e6" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>EIPD_OUTPUTS_LENGTH</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>WORD#16#0</InitValue>
        <DataType>WORD</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="5" ObjectId="/PDList/PD[@uid=eip006]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_7">
        <Label>EIPD_OUTPUTS_LENGTH</Label>
        <DataType>Bitstring16</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="65cff326-a1b4-4462-8121-1aca022abadf">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="91035257-58ac-46af-86ea-bcdd9f576150" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>EIPD_INPUTS_LENGTH</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>WORD#16#0</InitValue>
        <DataType>WORD</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.Uncopyable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.Undeletable, Ade.DataListImpl" Parameters="" />
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Comment,IsOpc,IsHmi,IsProficloud" />
      </Role>
      <Role TypeName="ProcessDatum" ObjectIndex="6" ObjectId="/PDList/PD[@uid=eip007]" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_7">
        <Label>EIPD_INPUTS_LENGTH</Label>
        <DataType>Bitstring16</DataType>
        <IsSafe>False</IsSafe>
        <Access>Read</Access>
        <Offset />
        <Constraint TypeName="Ade.DataList.Constraints.Unsplitable, Ade.DataListImpl" Parameters="Variable|ProcessDatum" />
      </Role>
    </Datum>
    <Datum Uuid="7613da31-f1ec-4680-bb57-6c5a0847f53c">
      <FunctionText />
      <Role TypeName="Variable" ObjectId="01c631a9-60c6-4f4c-a89f-d5d818df0962" SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75">
        <IsProficloud>False</IsProficloud>
        <Name>PLC</Name>
        <Address />
        <IsHmi>False</IsHmi>
        <InitValue>FALSE</InitValue>
        <DataType>BOOL</DataType>
        <IsRetain>False</IsRetain>
        <Comment />
        <IsOpc>False</IsOpc>
        <Usage>Global</Usage>
        <IsRedundant>False</IsRedundant>
        <IsConstant>False</IsConstant>
        <Constraint TypeName="Ade.DataList.Constraints.EditableAttributes, Ade.DataListImpl" Parameters="Name,Usage,DataType,InitValue,IsRetain,Comment,IsOpc,IsConstant,IsHmi,IsProficloud,IsRedundant" />
      </Role>
    </Datum>
    <Datum Uuid="d0ea1867-de28-4cc1-8c20-625c39797df3">
      <FunctionText />
      <Role TypeName="InPort" ObjectId="4a62de6b-6ae7-4d30-a4c3-93a9e8664b0c" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_2">
        <IsProficloud>False</IsProficloud>
        <Name>AX_Inputs</Name>
        <Program>Arp.Plc.Eclr / MainInstance</Program>
        <ComponentInstance>Arp.Plc.Eclr</ComponentInstance>
        <PortDataType>PND_IO_512</PortDataType>
        <IsHmi>False</IsHmi>
        <PortMultiplicity>1</PortMultiplicity>
        <PortDataTypeDomain>Iec</PortDataTypeDomain>
        <DataType>PND_IO_512</DataType>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsRedundant>False</IsRedundant>
        <Index />
        <ProgramInstance>MainInstance</ProgramInstance>
      </Role>
      <Role TypeName="OutPort" ObjectId="/PDList/PD[@uid=iodpdin]" SourceId="1c4661d2-10ca-4650-b083-963b1bee6704">
        <IsProficloud>False</IsProficloud>
        <Name>DI4096</Name>
        <Program>Arp.Io.AxlC</Program>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <NodeId>0</NodeId>
        <PortDataType>Octetstring[512]</PortDataType>
        <IsHmi>False</IsHmi>
        <PortMultiplicity>1</PortMultiplicity>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <DataType>Octetstring[512]</DataType>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsRedundant>False</IsRedundant>
        <Index>0.0</Index>
        <Offset>0.0</Offset>
      </Role>
    </Datum>
    <Datum Uuid="a28d17e5-3a81-47fc-8311-226275ed0b7e">
      <FunctionText />
      <Role TypeName="OutPort" ObjectId="9cd8f0a7-c7fa-428c-b375-1be29233c1a4" SourceId="b84580d7-61ea-48ec-9861-abe43adbd376.L7_2">
        <IsProficloud>False</IsProficloud>
        <Name>AX_Outputs</Name>
        <Program>Arp.Plc.Eclr / MainInstance</Program>
        <ComponentInstance>Arp.Plc.Eclr</ComponentInstance>
        <PortDataType>PND_IO_512</PortDataType>
        <IsHmi>False</IsHmi>
        <PortMultiplicity>1</PortMultiplicity>
        <PortDataTypeDomain>Iec</PortDataTypeDomain>
        <DataType>PND_IO_512</DataType>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsRedundant>False</IsRedundant>
        <Index />
        <ProgramInstance>MainInstance</ProgramInstance>
      </Role>
      <Role TypeName="InPort" ObjectId="/PDList/PD[@uid=iopdout]" SourceId="1c4661d2-10ca-4650-b083-963b1bee6704">
        <IsProficloud>False</IsProficloud>
        <Name>DO4096</Name>
        <Program>Arp.Io.AxlC</Program>
        <ComponentInstance>Arp.Io.AxlC</ComponentInstance>
        <NodeId>0</NodeId>
        <PortDataType>Octetstring[512]</PortDataType>
        <IsHmi>False</IsHmi>
        <PortMultiplicity>1</PortMultiplicity>
        <PortDataTypeDomain>Fdcml</PortDataTypeDomain>
        <DataType>Octetstring[512]</DataType>
        <IsRetain>False</IsRetain>
        <IsOpc>False</IsOpc>
        <IsRedundant>False</IsRedundant>
        <Index>0.0</Index>
        <Offset>0.0</Offset>
      </Role>
    </Datum>
    <RoleGroupList RoleTypeName="Variable">
      <RoleGroup SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75" ObjectId="fb84caa8-36a3-47d9-8bf0-95ff0e8a7b24" DisplayName="Default" IsReadOnly="False">
        <RoleDatumUuid>7613da31-f1ec-4680-bb57-6c5a0847f53c</RoleDatumUuid>
      </RoleGroup>
      <RoleGroup SourceId="adeprojectref:///e639c0f9-db09-46f4-abf7-50216a13f220/606e2993-1c57-411c-b0d2-c57a13c52bbf/9c176e32-8058-4821-b2cd-c43fbd816f75" ObjectId="971398c9-e054-4349-a1d9-e00a1840c9f4" DisplayName="System Variables" IsReadOnly="True">
        <RoleDatumUuid>ae807d18-40f0-4651-966c-6f4a5563fe17</RoleDatumUuid>
        <RoleDatumUuid>b2e506b5-4e43-4341-a5f1-2b04e2cf0fc8</RoleDatumUuid>
        <RoleDatumUuid>fe6f0710-0257-4801-b8df-e2490df12ecd</RoleDatumUuid>
        <RoleDatumUuid>a46cf355-0298-4697-a781-e34295307a6f</RoleDatumUuid>
        <RoleDatumUuid>ea80c21f-2ab8-4174-8705-83ce9c3f347f</RoleDatumUuid>
        <RoleDatumUuid>453dc524-726f-4d74-bb90-fe6cd5d7db49</RoleDatumUuid>
        <RoleDatumUuid>ad6b20cb-a783-4511-b0ec-f5c4847ea448</RoleDatumUuid>
        <RoleDatumUuid>4fe76df1-d38d-4401-9499-18ce1dcc86c5</RoleDatumUuid>
        <RoleDatumUuid>44a868a2-ec2b-4e0c-abd6-ef4d93b9f3ef</RoleDatumUuid>
        <RoleDatumUuid>2e5f3914-6006-43a2-ac3e-5d6d98e949d1</RoleDatumUuid>
        <RoleDatumUuid>84a1f344-5bc2-4fe3-94ef-7bcb573584df</RoleDatumUuid>
        <RoleDatumUuid>82d2b4a1-69c0-42ca-a39f-85fbe754f8f2</RoleDatumUuid>
        <RoleDatumUuid>e94f4aff-b669-43d2-a75e-417a559b95f7</RoleDatumUuid>
        <RoleDatumUuid>7c64937b-172d-486d-9070-da3a76ce6eeb</RoleDatumUuid>
        <RoleDatumUuid>761d3054-7bf2-410c-b9ef-d759d7516860</RoleDatumUuid>
        <RoleDatumUuid>8cda5a17-62ba-4745-8715-251dc8a43b48</RoleDatumUuid>
        <RoleDatumUuid>971bf69a-7d88-4b3f-bbaa-0bcebd110410</RoleDatumUuid>
        <RoleDatumUuid>992715bb-1594-4f65-be5d-16082e044c67</RoleDatumUuid>
        <RoleDatumUuid>eaf31e0c-6d1e-401f-832d-f6394207ad20</RoleDatumUuid>
        <RoleDatumUuid>2f73cf55-d1d6-4283-a17f-ec89086df4d3</RoleDatumUuid>
        <RoleDatumUuid>5985b134-d8c1-4a0f-8121-bdbc4bda409b</RoleDatumUuid>
        <RoleDatumUuid>a1ec2a5e-ff93-46a9-91cd-98a48a3059b0</RoleDatumUuid>
        <RoleDatumUuid>854e583c-2a72-41f9-af44-05b78adb3dae</RoleDatumUuid>
        <RoleDatumUuid>62765bcc-12e0-4ee7-904c-c8a059d7384b</RoleDatumUuid>
        <RoleDatumUuid>fecba4c5-bacd-42aa-bedb-34f9c5a946d3</RoleDatumUuid>
        <RoleDatumUuid>06f9910e-36fe-4227-97c2-bd7012ad31bc</RoleDatumUuid>
        <RoleDatumUuid>10ca3869-a68e-41de-ad04-253ab51ad3db</RoleDatumUuid>
        <RoleDatumUuid>445dbc67-11fb-4ee3-8e76-1cfb24557564</RoleDatumUuid>
        <RoleDatumUuid>ff1b6de6-0c92-4860-b74e-a12ab491e407</RoleDatumUuid>
        <RoleDatumUuid>329e576e-cd01-4c36-8513-ed17b5205acf</RoleDatumUuid>
        <RoleDatumUuid>7c40d2c8-938e-481d-b807-969b4737b18e</RoleDatumUuid>
        <RoleDatumUuid>a40530ae-d70a-4155-8bd4-94776b2a8724</RoleDatumUuid>
        <RoleDatumUuid>9be96f1b-360a-47d9-aa0a-8cc17cc72c17</RoleDatumUuid>
        <RoleDatumUuid>d7c3d270-3bbd-4b4c-a3af-a52c00df211b</RoleDatumUuid>
        <RoleDatumUuid>d2f05920-efb7-421e-9d23-f0ad329cbdc1</RoleDatumUuid>
        <RoleDatumUuid>e43a9a43-3b79-4501-805c-341416cbf314</RoleDatumUuid>
        <RoleDatumUuid>4dc55292-9e6d-4668-882a-0be2953e48be</RoleDatumUuid>
        <RoleDatumUuid>86e1d7ad-7244-44b4-aab0-1f88f7db169a</RoleDatumUuid>
        <RoleDatumUuid>46f989b9-2b49-41c7-a2a1-e6ff7fbcaf9d</RoleDatumUuid>
        <RoleDatumUuid>9a63bd46-1a87-4835-9f54-36dcbc58a497</RoleDatumUuid>
        <RoleDatumUuid>7fb15367-2f7d-43cc-b851-9666bc2d93fd</RoleDatumUuid>
        <RoleDatumUuid>9d305870-ef62-443e-b4f7-9597b9d7fcb0</RoleDatumUuid>
        <RoleDatumUuid>c8578976-c67e-4bc3-8570-5d032d21c66f</RoleDatumUuid>
        <RoleDatumUuid>514c4196-d8c8-4816-a515-eef0bfded2ac</RoleDatumUuid>
        <RoleDatumUuid>426883ca-4a33-4e62-9b3d-59435b44e7bf</RoleDatumUuid>
        <RoleDatumUuid>1caa948f-8b6b-4c45-89e9-774507c125cd</RoleDatumUuid>
        <RoleDatumUuid>6fea7671-704f-45d6-be4a-eaa2cdb6279a</RoleDatumUuid>
        <RoleDatumUuid>86bf508d-2a43-4069-9e1f-f9402c133000</RoleDatumUuid>
        <RoleDatumUuid>c0bd5c4f-aa78-4961-8fb5-bde4af950fc6</RoleDatumUuid>
        <RoleDatumUuid>ef204237-fa98-434c-b91f-d17e200683cd</RoleDatumUuid>
        <RoleDatumUuid>030cd920-e53a-4ae2-8657-f76524131aeb</RoleDatumUuid>
        <RoleDatumUuid>bacb7935-8852-4173-a6c6-bad305088ec8</RoleDatumUuid>
        <RoleDatumUuid>7ce3742a-f684-4913-a032-9a707654007a</RoleDatumUuid>
        <RoleDatumUuid>bd258abb-5829-4b71-9a6c-d29148089a83</RoleDatumUuid>
        <RoleDatumUuid>d5918e54-0745-4246-9107-d143d6256879</RoleDatumUuid>
        <RoleDatumUuid>27f5af69-941a-489a-b8e7-d1d55fba9e0f</RoleDatumUuid>
        <RoleDatumUuid>77142c55-72a3-45bc-8e70-11aec5297d6e</RoleDatumUuid>
        <RoleDatumUuid>15f51bbf-e345-435b-be66-66037706fb7b</RoleDatumUuid>
        <RoleDatumUuid>d8993079-2be0-486e-822e-49987817cde2</RoleDatumUuid>
        <RoleDatumUuid>d2d42752-7083-4fce-b7e1-a47cb78286ba</RoleDatumUuid>
        <RoleDatumUuid>2be6bf5f-6326-4f22-8c17-14a29de77a22</RoleDatumUuid>
        <RoleDatumUuid>65cff326-a1b4-4462-8121-1aca022abadf</RoleDatumUuid>
      </RoleGroup>
    </RoleGroupList>
    <RoleGroupList RoleTypeName="SafetyVariable" />
  </DataList>
</DataListDocument>